### ISSUE TITLE
Villumelding

### ISSUE THREAD

**Issue by lsjomoen** [siggib007/phptest#43]
Ég bjó til nýja síðusem heitir "´g ætla að prófa þetta", enn þegar ég opnaði hana kom villuskilaboð?

Administration tasks

We seem to be experiencing some technical difficulties, hopefully we'll have it resolved shortly.
If you have any questions please contact us at support@example.com.

**Comment by siggib007** [comment]
Can this be reproduced? I can't find this page.

**Comment by siggib007** [comment]
Found it. The issue was illegal characters in the file name. Good job finding this bug. Implemented a check filters out all undesireables.
