### ISSUE TITLE
Villuskilaboð í Menu Admin

### ISSUE THREAD

**Issue by lsjomoen** [siggib007/phptest#45]
Var í Menu Maintenance, var í neðsta línan og ýtti á edit.
Þá kom villuskilaboð:

Menu Maintenace

We seem to be experiencing some technical difficulties, hopefully we'll have it resolved shortly.
If you have any questions please contact us at support@example.com.

**Comment by lsjomoen** [comment]
Sama villuskilaboð kemur í miðkaflan og efra kaflan þegar ég ýti á edit.

**Comment by siggib007** [comment]
fixed
